### ISSUE TITLE
batch first mode causes some error

### ISSUE THREAD

**Issue by GuanlinLee** [exe1023/LSTM_LN#1]
`if __name__ == '__main__':

    model = LSTM(50, 100, 2,batch_first=True)

    x = Variable(Tensor(32,50, 50))

    h = model.init_hidden(32)

    print(model(x, h))`

and it will return :

`Traceback (most recent call last):'

  'File "lstm.py", line 379, in <module>'

  '  print(model(x, h))'

'  File "Python\Python35\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__'

'    result = self.forward(*input, **kwargs)'

 ' File "lstm.py", line 92, in forward'

  '  f_x, f_h = self.layer_forward(l, x, h, image_emb)'

 ' File "lstm.py", line 72, in layer_forward'

  '  y, h = l(x, h, image_emb)'

 ' File "Python\Python35\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__'

 '   result = self.forward(*input, **kwargs)'

'  File "lstm.py", line 336, in forward'

 '   preact = i2h + h2h'

'RuntimeError: The size of tensor a (50) must match the size of tensor b (32) at non-singleton dimension 0`

**Comment by exe1023** [comment]
Actually I forgot to implement the batch_first mode...

**Comment by NiziL** [comment]
If someone is still having this issue currently, I've solved it by switching this piece of code
```python
if self.batch_first:
    x = x.permute(1, 0, 2)
```
from the end of `forward` to the end of `layer_forward`.

Basically, the output of `layer_forward` was not "batch first", so when this output is fed to the second layer, the `permute(1, 0, 2)` at the beginning of `layer_forward` mess up the computation.

Btw, I've also worked on making the module compatible with sequences of variables lengths. It's not very efficient, but it seems to work... If someone want it, feel free to contact me.

**Comment by SpursGoZmy** [comment]
> If someone is still having this issue currently, I've solved it by switching this piece of code
> 
> ```python
> if self.batch_first:
>     x = x.permute(1, 0, 2)
> ```
> 
> from the end of `forward` to the end of `layer_forward`.
> 
> Basically, the output of `layer_forward` was not "batch first", so when this output is fed to the second layer, the `permute(1, 0, 2)` at the beginning of `layer_forward` mess up the computation.
> 
> Btw, I've also worked on making the module compatible with sequences of variables lengths. It's not very efficient, but it seems to work... If someone want it, feel free to contact me.

Hi! Dear Nizil:
       I am an undergraduate from China. Recently,  I have been working on reimplementing a paper which uses the LN-LSTM. I noticed you solved the problem of "batch_first" and also made this module compatible with sequences of variables lengths. Could you provide a copy of your improved LN-LSTM? It would be definitely helpful! If you create a repository, a lot of students will be star it! hhhhh ^-^.  Best wish.

**Comment by NiziL** [comment]
@bnucist-zmy Almost 3 month, I'm so sorry about the delay... I've just opened a PR to fix this issue. If you need to work with variable length, you can find a "var_length" branch in my fork ;)

**Comment by SpursGoZmy** [comment]
> @bnucist-zmy Almost 3 month, I'm so sorry about the delay... I've just opened a PR to fix this issue. If you need to work with variable length, you can find a "var_length" branch in my fork ;)
That's fine~~Thanks a lot for your excellent code! I really appreciate it. There is no doubt that it would helps a lot of NLP researcher.

**Comment by vipbze** [comment]
I solve this case by add 'y = y.permute(1, 0, 2).contiguous()' in layer_forward:

    def layer_forward(self, l, xs, h, image_emb, reverse=False):
        '''
        return:
            xs: (seq_len, batch, hidden)
            h: (1, batch, hidden)
        '''
        if self.batch_first:
            xs = xs.permute(1, 0, 2).contiguous()
        ys = []
        for i in range(xs.size(0)):
            if reverse:
                x = xs.narrow(0, (xs.size(0)-1)-i, 1)
            else:
                x = xs.narrow(0, i, 1)
            y, h = l(x, h, image_emb)
            ys.append(y)
        y = torch.cat(ys, 0)
        # added code
        if self.batch_first:
            y = y.permute(1, 0, 2).contiguous()
        return y, h
